import type { Product } from "./types"

export const products: Product[] = [
  {
    id: 1,
    name: "Backpack",
    description:
      "A stylish and durable backpack for everyday use. Features multiple compartments and padded laptop sleeve.",
    price: 49.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    inventory: 15,
  },
  {
    id: 2,
    name: "T-Shirt",
    description: "Comfortable cotton t-shirt with a modern fit. Available in multiple colors and sizes.",
    price: 19.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Clothing",
    inventory: 25,
  },
  {
    id: 3,
    name: "Water Bottle",
    description: "Insulated stainless steel water bottle that keeps drinks cold for 24 hours or hot for 12 hours.",
    price: 24.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    inventory: 10,
  },
  {
    id: 4,
    name: "Sneakers",
    description: "Lightweight and comfortable sneakers perfect for running or casual wear.",
    price: 79.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Footwear",
    inventory: 8,
  },
  {
    id: 5,
    name: "Headphones",
    description: "Wireless over-ear headphones with noise cancellation and long battery life.",
    price: 129.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    inventory: 5,
  },
  {
    id: 6,
    name: "Laptop Sleeve",
    description: "Protective sleeve for laptops up to 15 inches. Made with water-resistant material.",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    inventory: 12,
  },
  {
    id: 7,
    name: "Sunglasses",
    description: "Stylish sunglasses with UV protection. Lightweight and durable frame.",
    price: 59.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Accessories",
    inventory: 7,
  },
  {
    id: 8,
    name: "Smartwatch",
    description: "Feature-packed smartwatch with fitness tracking, notifications, and long battery life.",
    price: 199.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    inventory: 3,
  },
  {
    id: 9,
    name: "Hoodie",
    description: "Warm and comfortable hoodie made from premium cotton blend. Perfect for cooler weather.",
    price: 44.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Clothing",
    inventory: 18,
  },
  {
    id: 10,
    name: "Desk Lamp",
    description: "Adjustable LED desk lamp with multiple brightness levels and color temperatures.",
    price: 34.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Home",
    inventory: 9,
  },
  {
    id: 11,
    name: "Wireless Charger",
    description: "Fast wireless charger compatible with all Qi-enabled devices.",
    price: 29.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Electronics",
    inventory: 14,
  },
  {
    id: 12,
    name: "Coffee Mug",
    description: "Ceramic coffee mug with minimalist design. Dishwasher and microwave safe.",
    price: 14.99,
    image: "/placeholder.svg?height=300&width=300",
    category: "Home",
    inventory: 20,
  },
]
